import Head from 'next/head'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Info from '../components/Info'
import Last from '../components/Last'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
      </Head>
      <header>
        <Navbar></Navbar>
      </header>
      <body className="grid grid-cols-1 grid-rows-3 h-[600vw] md:h-fit lg:h-fit">
        <Hero></Hero>
        <Info></Info>
        <Last></Last>
      </body>
    </div>
  )
}
