import Head from 'next/head'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Info from '../components/Info'
import Last from '../components/Last'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
      </Head>
      <header>
        <Navbar></Navbar>
      </header>
      <body className="grid grid-cols-1 grid-rows-3 h-[800vw] sm:h-[160vw] w-[200vw] sm:w-[100vw] ">
        <Hero></Hero>
        <Info></Info>
        <Last></Last>
      </body>
      <footer class="p-4 bg-white rounded-lg shadow md:px-6 md:py-8 dark:bg-gray-900">
        <div class="sm:flex sm:items-center sm:justify-between">
          <a href="/" class="flex items-center mb-4 sm:mb-0">
            <img src="logo_eve_ne.svg" class="h-8 mr-3" alt="eve logo" />
          </a>
          <ul class="flex flex-wrap items-center mb-6 text-sm text-gray-500 sm:mb-0 dark:text-gray-400">
            <li>
              <a href="#" class="mr-4 hover:underline md:mr-6 ">
                About
              </a>
            </li>
            <li>
              <a href="#" class="mr-4 hover:underline md:mr-6">
                Privacy Policy
              </a>
            </li>
            <li>
              <a href="#" class="mr-4 hover:underline md:mr-6 ">
                Licensing
              </a>
            </li>
            <li>
              <a href="mailto:hola@evemed.ar" class="hover:underline">
                Contact
              </a>
            </li>
          </ul>
        </div>
        <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
        <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">
          ©{' '}
          <a href="/" class="hover:underline">
            eve™
          </a>
          . All Rights Reserved.
        </span>
      </footer>
    </div>
  )
}
